const Recipe = require("../models/Recipe");
require("../models/database");
exports.insertIngredientData = async (req, res) => {
  try {
    await Recipe.insertMany([
      {
        name: "Spicy Chicken Pad Thai",
        type: "Entree",
        ingredients: [
          "4 oz flat rice noodles",
          "3 tbsp canola oil, divided",
          "1/2 lb. chicken breast, sliced into very thin strips",
          "1/2 red bell pepper, halved and thinly sliced",
          "3/4 cup carrots, shredded or julienned",
          "2 garlic cloves, minced",
          "1 egg, beaten",
          "1 green onion, chopped",
          "1/4 cup unsalted peanuts, roughly chopped",
          "2 tbsp cilantro leaves, chopped",
          "2 tbsp packed brown sugar",
          "1 tbsp low sodium soy sauce",
          "1 tbsp fish sauce",
          "1 tbsp lime juice",
          "1 tbsp rice vinegar",
          "1 tbsp smooth peanut butter",
          "1 tbsp Sriracha or another chili paste",
          "1/4 tsp ground ginger",
          "1/8 tsp pepper",
        ],
        category: "Asian",
        instructions: [
          "1.Prepare rice noodles according to package directions. Rinse noodles in cold water, drain, and toss in with 1 tbsp canola oil. Set aside.",
          "2. Add all of the sauce ingredients to a medium mixing bowl. Whisk together and set aside.",
          "3. While rice noodles are soaking, heat 1 tablespoon canola oil in a large nonstick skillet over medium-high heat. Once hot, add chicken and let cook for 3-4 minutes until cooked through. Transfer to a plate while you cook the vegetables.",
          "4. Heat one tablespoon canola oil over in the same skillet and heat over medium-high heat. Add bell peppers and sauté 1 minute. Add carrots and garlic and sauté 1 additional minute. Reduce heat to medium and pour beaten egg over vegetables and cook, stirring constantly, just until scrambled.",
          "5. Add sauce and noodles and increase heat to medium-high. Toss until evenly combined and continue to stir and cook for 1-2 minutes, taking care to not let noodles overcook. Stir in chicken, green onions and peanuts, and heat through.",
          "6. Taste and add one additional seasoning as necessary. You can add more Sriracha if you want it spicier, soy sauce for a salty bite, or a squeeze of lime for a tang. Top with cilantro and serve.",
        ],
      },
      {
        name: "Hot Chicken Chili",
        type: "Entree",
        ingredients: [
          "Vegetable oil",
          "cayenne pepper",
          "brown sugar",
          "paprika",
          "garlic powder",
          "kosher salt",
          "carrot",
          "yellow onion",
          "ground chicken",
          "white chili beans",
          "Pinto Beans",
          "diced tomatoes",
          "hot sauce",
          "chicken broth",
          "pickle brine",
          "sour cream",
          "shredded cheddar",
        ],
        category: "American",
        instructions: [
          "1. Add the oil to a Dutch oven, set over medium heat. When the oil is simmering, add the cayenne, brown sugar, paprika, garlic powder, and salt. Cook over low heat until the spices infuse the oil, 2 to 3 minutes.",
          "2. Add the carrots and onion, and cook until the vegetables soften and start to brown, 6 to 8 minutes. Add the chicken and cook, breaking up the chicken with a wooden spoon, until browned, 4 to 5 minutes. Add BUSH’S® Chili Beans, tomatoes, and hot sauce. Stir together and bring to a simmer. Pour in the broth. Return to a simmer and cook, partially covered, stirring occasionally, until the chili is thickened, 15 to 20 minutes.",
          "3. Ladle the chili into bowls. Top each bowl with a dollop of sour cream, a sprinkle of shredded cheddar, and more hot sauce, if desired.",
        ],
      },
      {
        name: "Strawberry Jalapeno Baby Back Ribs",
        type: "Entree",
        ingredients: [
          "1 teaspoon olive oil",
          "2 Tablespoons white onion, diced",
          "1 small jalapeno, diced (remove seeds if you don’t like things too spicy",
          "1 tablespoon garlic, minced",
          "3/4 cup cola",
          "3/4 cup strawberry preserves",
          "1 24 oz. package Curly’s Baby Back Pork Ribs",
          "Sliced jalapeno and strawberries to garnish, if desired",
        ],
        category: "American",
        instructions: [
          "1. Heat olive oil in a small saucepan over medium heat. Add onion, jalapeno, and garlic and saute until fragrant and tender, 3-5 minutes. Stir in cola, and strawberry preserves. Turn heat to low and allow to simmer 6-8 minutes thickened. Set aside.",
          "2. Heat gas or charcoal grill to medium. Remove ribs from package and place on grill. Brush with strawberry jalapeno glaze and grill for 10 minutes. Rotate ribs and brush with more glaze. Grill for an additional 10-15 minutes as needed. Garnish with sliced jalapeno and strawberries, if desired.",
        ],
      },
      {
        name: "Spicy Chorizo Kale Tacos With Mushrooms and Avocado Crema",
        type: "Entree",
        ingredients: [
          "2 ripe avocados",
          "juice of 1 lime",
          "1/4 cup fresh cilantro",
          "1/2 tsp sal",
          "8 corn tortillas",
          "1 lb fresh chorizo",
          "1 cup white mushrooms, quartered",
          "2 cups kale, stripped off the stem, and coarsely chopped",
          "1/2 cup crumbled feta or cotija cheese",
          "fresh cilantro to garnish",
        ],
        category: "Mexican",
        instructions: [
          "1. For the Avocado Crema",
          "2. Add avocado, lime juice, cilantro, and salt to a small food processor or blender. Blend until avocados are smooth and creamy. If the mixture looks too thick for drizzling, add a couple of tbsp of water or milk. Set aside.",
          "For Tacos",
          "3. Heat a large skillet over medium-high heat. Brown chorizo, breaking up the sausage with a wooden spoon. When the chorizo is browned, add mushrooms and cook until soft.",
          "4. Warm tortillas in the microwave or in a very low oven.",
          "5. To Assemble",
          "6. Layer chopped kale on the bottom of a warm tortilla. Top with a few tbsp of chorizo and mushroom mixture and sprinkle on cheese, as desired. Drizzle on prepared avocado crema and garnish with cilantro.",
        ],
      },
      {
        name: "Sweet Potato Salad with Bacon and Spiced Pecans",
        type: "Appetizer",
        ingredients: [
          "4 each Sweet potatoes, large, peeled and diced 1-inch square.",
          "8 ounces bacon, diced",
          "1 each Red onion, small diced",
          "3 each Garlic cloves, minced",
          "2 Tablespoons fresh Lemon Juice",
          "1 bunch Scallions, sliced thin",
          "2 cups Mayonnaise",
          "Kosher Salt to taste",
          "Black Pepper to taste",
          "2 cups spicy pecans, roughly chopped",
        ],
        category: "American",
        instructions: [
          "1. Peel and dice the potatoes and put them in a pot of cold water with 2 T of salt. Bring the water to a boil. Once the water reaches a boil, turn down the heat and let the water simmer.",
          "2. Cook the potatoes until they are tender. Drain and lay the potatoes on a sheet pan. Put the potatoes in the refrigerator and let them cool.",
          "3. Cook the bacon until crisp. Drain and reserve the fat. Let the bacon cool to room temperature.",
          "4. Dice up the red onion, garlic, and scallions. Cook the red onion in a little bit of olive oil until they are soft. Then add the garlic and cook for 2 more minutes. Let the onion and garlic cool to room temperature. Keep the scallion raw.",
          "5. Take the bacon fat and add it to the mayo along with the lemon juice, red onion, garlic, and scallions. Season to taste with salt and black pepper.",
          "6. Add the mayo mixture to the chilled sweet potatoes.",
          "7. Season to taste with the Salt and Black Pepper.",
          "8. Just before serving, stir in the spicy pecans.",
        ],
      },
      {
        name: "Corn and Pepper Jack Hush Puppies",
        type: "Appetizer",
        ingredients: [
          "1 cup cornmeal",
          "1/2 cup flour",
          "1 teaspoon salt",
          "1 teaspoon baking powder",
          "2 teaspoon sugar",
          "1/2 cup shredded pepper jack cheese",
          "1/4 cup white onion, diced",
          "1 egg",
          "1 cup buttermilk",
          "1/2 cup fresh or defrosted frozen corn",
          "oil for frying",
        ],
        category: "American",
        instructions: [
          "1.  Combine all the ingredients in a bowl and mix to combine, being careful not to over mix. It's ok if the batter is a little lumpy.",
          "2.  Heat at least 2-3 cups of high smoke-point oil to 350ºF in a dutch oven.",
          "3. Using a medium-sized cookie scoop, drop scoops of the batter in the hot oil, being careful not to overcrowd the pan.",
          "4. Fry for about 2-3 minutes then flip over and fry another 2-3 minutes. They should be golden brown on all sides.",
          "5.  Using a spider or slotted spoon, remove the hushpuppies from the oil and drain them on paper towels or a wire rack. Serve warm with an aioli or ketchup.",
        ],
      },
      {
        name: "Honey Butter Mint Glazed Meatballs",
        type: "Appetizer",
        ingredients: [
          "1 cup Panko Breadcrumbs",
          "1/3 cup milk",
          "1 pound ground beef",
          "1 pound ground pork",
          "4 cloves garlic, minced",
          "2 eggs",
          "1 cup grated parmesan cheese",
          "1 cup grated yellow onion",
          "2 teaspoons Worcestershire sauce",
          "1 teaspoon salt",
          "1/2 teaspoon black pepper",
          "1/4 teaspoon crushed red pepper flakes",
          "Glaze",
          "6 tablespoons salted butter",
          "1/3 cup honey",
        ],
        category: "American",
        instructions: [
          "1. Preheat the oven to 425°F and line a large rimmed baking sheet with parchment paper.",
          "2. In a large mixing bowl, stir together the panko and milk until combined. Set mixture aside to soak for 5 to 10 minutes while you prepare the other ingredients.",
          "3. Add the ground beef, ground pork, garlic, eggs, Parmesan, onion, and Worcestershire sauce to the panko mixture. Season with salt, black pepper, and crushed red pepper. Use your hands to mix the ingredients until evenly combined, being careful not to over-mix the ingredients.",
          "4. Using a medium cookie scoop or a spoon, scoop and roll the mixture into 2-tablespoon balls and place them on the prepared baking sheet. Keeping your hands oiled helps keep the meat from sticking to you too bad.",
          "5. Bake for 10-12 minutes, or until an instant-read thermometer measures the internal temperature of the meatballs to be 160°F.",
          "6. While the meatballs are baking, make the glaze. In a small saucepan, combine the butter, honey, mint, and garlic. Bring to a boil and whisk until smooth. Simmer for about 5 minutes until thickened. Discard the smashed garlic.",
        ],
      },
      {
        name: "Vegetarian Winter Squash Nachos",
        type: "Appetizer",
        ingredients: [
          "1/2 cup sour cream",
          "1/2 cup mayonnaise",
          "1/4 teaspoon garlic powder",
          "1/3 cup fresh cilantro",
          "1/2 cup pickled jalapeños + 1/4 cup of the juice from the jar",
          "1/4 cup buttermilk",
          "2 teaspoons fresh lime juice",
          "12 oz cubed butternut squash",
          "1 bag Tortilla chips",
          "1 14 oz can vegetarian refried pinto beans",
          "3 cups shredded cheddar cheese",
          "1 cup crumbled cotija cheese",
          "1/4 cup pickled jalapeños",
          "1 cup pomegrante arils",
          "scallions, thinly sliced",
          "fresh cilantro, chopped, to serve",
        ],
        category: "Mexican",
        instructions: [
          "1. Prepare the Jalapeño Sauce. In a blender or food processor, puree the sour cream, mayo, garlic powder, cilantro, pickled jalapenos with their juice, buttermilk, and lime juice until smooth. Refrigerate until ready to serve.",
          "2. Transfer the cubed butternut squash to a lined baking sheet and toss with a bit of olive oil and salt and pepper. Place in a preheated 400°F oven and bake for 30-35 minutes, until the squash is tender and golden brown.",
          "3. If you're like me and don't want to dirty more dishes, transfer the butternut squash off of the baking sheet and line it with new parchment to build your nachos.",
          "4 .Turn oven up to 425°F. Arrange half of the chips on the baking sheet. Dollop with half of the beans, then half of the shredded cheddar cheese, and half of the roasted butternut squash.",
          "5. Repeat layering with remaining chips, beans, cheese, and squash. Bake until cheese is melted and gooey, about 5 minutes.",
          "6. Top the nachos with cotija cheese, pomegranates, pickled jalapeño, scallions, and cilantro. Drizzle with the jalapenño sauce to serve.",
        ],
      },
      {
        name: "Chocolate Gingerbread Mini Muffins",
        type: "Dessert",
        ingredients: [
          "1/2 cup unsalted butter",
          "3/4 cup dark molasses",
          "2 and 2/3 cups all-purpose flour",
          "1 and 1/2 teaspoons baking soda",
          "1/4 teaspoon salt",
          "1 and 1/2 teaspoons ground cinnamon",
          "1 and 1/4 teaspoons ground ginger",
          "1/2 teaspoon ground cloves",
          "1/2 cup packed light or dark brown sugar",
          "1 large egg, at room temperature",
          "1/2 cup sour cream, at room temperature",
          "1/2 cup whole milk, at room temperature",
          "1 cup mini chocolate chips",
          "powdered sugar for sprinkling the tops, optional",
        ],
        category: "American",
        instructions: [
          "1. Preheat oven to 350°F. Grease a mini muffin pan with butter or nonstick spray or line with mini cupcake liners. Set aside.",
          "2. In a small saucepan over medium heat, melt the butter and molasses together. Stir until thoroughly mixed together and melted. Set aside to cool as you mix the dry ingredients together.",
          " 3. Whisk the flour, baking soda, salt, cinnamon, ginger, and cloves together.",
          " 4. Into the molasses/butter mixture, whisk the brown sugar, egg, sour cream, and milk until all wet ingredients are combined. Pour wet ingredients into dry ingredients and mix until just combined. Do not over-mix. Fold in mini chocolate chips.",
          " 5. Divide batter among prepared muffin pan, filling all the way to the top. Bake for 11-12 minutes until the centers are set. You can use a toothpick inserted in the center to test but keep in mind the melted chocolate chips could throw you off. Allow the muffins to cool for 5-10 minutes in the pan before removing muffins to a cooling rack to cool completely. Dust with powdered sugar once cooled, if desired.",
        ],
      },
      {
        name: "Chocolate chip-espresso icebox cake",
        type: "Dessert",
        ingredients: [
          "340g mascarpone cheese",
          "450 ml heavy cream",
          "100 g granulated sugar",
          "1 tbsp instant espresso powder",
          "2 tbsp cocoa powder",
          "1 tsp vanilla extract",
          "24 chocolate chip cookies (store-bought or homemade)",
          "semisweet chocolate for garnish",
        ],
        category: "American",
        instructions: [
          "1. Using a stand or hand mixer fitted with the whisk attachment, beat cream, mascarpone cheese, powdered sugar, and vanilla extract. Start the mixer slow, then gradually increase the speed to medium-high and beat until stiff peaks form about 3-4 minutes. Taste, and if you'd prefer it sweeter you can add 2-3 more tablespoons of powdered sugar.",
          "2. Place one layer of cookies in the bottom of an 8x8 square baking dish. Break the cookies as needed to cover the bottom as much as possible; about 6-8 cookies per layer. Drizzle 1/4th of the espresso directly on top of the cookies - about 1 tablespoon. Then top with one-quarter of the whipped cream mixture, spreading it into an even layer. Repeat three more times: cookies, espresso, whipped cream - cookies, espresso, whipped cream - cookies, espresso, then the remaining whipped cream. Cover with plastic wrap and refrigerate for at least 6 hours, up to overnight",
          " 3. Sprinkle the top with mini chocolate chips, chocolate curls, or dust with cocoa powder and cut into squares to serve. Cover well and store for up to 3 days in the fridge.",
        ],
      },
    ]);
    res.send("complete");
  } catch (error) {
    console.log("err", error);
    res.send("error");
  }
};
